name: Build and push docker image

on:
  push:
    paths:
      - '.github/workflows/docker-image.yml'
      - 'Dockerfile'
      - 'python/poetry.lock'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: exercism-python
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
