name: CI

on:
  push:
    branches:
  pull_request:
    branches:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      python-image: ${{ steps.filter.outputs.pythong-image }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            python-image:
              paths:
                - .github/workflows/docker-image.yml
                - Dockerfile
                - python/poetry.lock
  # JOB to build a docker image for python
  build-python-image:
    runs-on: ubuntu-20.04
    needs: changes
    if: ${{ needs.changes.outputs.python-image == 'true' }}
    steps:
      -  uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push a docker image for python
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: exercism-python
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
  # JOB to test python tracks
  python:
    runs-on: ubuntu-20.04
    needs: build-python-image
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Test python exercises
        run: >-
          docker run --rm -v "${PWD}:/exercism/python" ghcr.io/${{ github.repository_owner }}/exercism-python
          pytest --cov --cov-branch --cov-fail-under=98
        working-directory: python
